apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapi
  template:
    metadata:
      labels:
        app: todoapi
    spec:
      containers:
      - name: todoapi
        image: raihan71/todo-node
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
